### ISSUE TITLE
Doesn't work with autotooltips plugin

### ISSUE THREAD

**Issue by high5five** [M0rtenB/dokuwiki-mredirect#3]

**Comment by high5five** [comment]
I'm using autotooltip with MRedirect and it causes redirects to **plugin-autotooltip_linked**

**Comment by zioth** [comment]
In `action.php`, you're creating the redirect by rendering the link as HTML, then doing string searches to extract the URL. This is not particularly future-proof (rendered links could look different in future versions of DokuWiki), and it interferes with renderer plugins like `autotooltips`.

To fix this, you can use the built-in functions of DokuWiki to create links.

```
      if (($all == '[[' . $inner . ']]') and (strpos ($inner, '[[') === false) and (strpos ($inner, ']]') === false)) {
          if (!strpos ($inner, '://') === false) {
              $url = $inner;    # link is URL already
          } else {
              msg (sprintf ('From: <a href="'.wl($ID,'do=edit').'">'.hsc($ID).'</a>'));
              $url = wl($inner);
          }
          idx_addPage($ID);  # ensure fulltext search indexing of referrer article - to put it on the backlink page of target article
          send_redirect($url);
      }
```

**Comment by high5five** [comment]
Used this post by you as a solution and it works.
https://github.com/zioth/dokuwiki-autotooltip/issues/9#issuecomment-473611716
Thanks again!
